version: "3.8"

services:
  tg-bot:
    build: .
    container_name: tg-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - BOT_TOKEN=""
    volumes:
      - ./data:/app/data
    command: python core.py
